version: "3.7"

services:
  backend:
    build:
      context: ./server  # Path to your backend folder
    container_name: nest-backend
    ports:
      - "3000:3000"  # Expose backend on port 3000
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: task_mgmt
      REDIS_HOST: redis
      JWT_SECRET: your-secret-key
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: task_mgmt
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"  # Expose Redis on port 6379

